### ISSUE TITLE
[BUG] download contract on ethereum got empty folder

### ISSUE THREAD

**Issue by shrimpliu** [MetaplasiaTeam/vscode-contract-viewer#3]
- VS Code Version: 1.64.2
- OS Version: OSX Monterey
- Contract Viewer Version: v0.0.5

**Describe the bug**
contract address is https://etherscan.io/address/0x960b7a6bcd451c9968473f7bbfd9be826efd549a#code

download success, but just got empty folder. I retried twice.

**Comment by Yanren1225** [comment]
[Fixed the unexpected analysis](https://github.com/MetaplasiaTeam/vscode-contract-viewer/commit/5660fba8650970d96906daf909ad0bc98e258017)
