### ISSUE TITLE
[BUG] Contract multiple files cannot be downloaded

### ISSUE THREAD

**Issue by aaronecgberht** [MetaplasiaTeam/vscode-contract-viewer#4]
BSC Contract multiple files cannot be downloaded

**Comment by Yanren1225** [comment]
Hello, can you provide the address of the contract that cannot be downloaded?

**Comment by aaronecgberht** [comment]
contract link: https://bscscan.com/address/0x0C950d28D71490199efD792f64aC3D68402bCE67#code

**Comment by aaronecgberht** [comment]
Is it still updated?

**Comment by Yanren1225** [comment]
> Is it still updated?

Sorry, I've been busy lately, I'll fix it within a week

**Comment by Yanren1225** [comment]
> 

Sorry for the long wait, it has been fixed
